### ISSUE TITLE
rstudio and r-sjplot-feedstock

### ISSUE THREAD

**Issue by andreifoldes** [conda-forge/r-sjplot-feedstock#21]
### Comment:

Hello - I'm having trouble installing r-sjplot-feestock and rstudio in the same anaconda environment? 
Its showing unsolvable conflicts - I'm using Windows 10.

**Comment by mfansler** [comment]
Currently, I would not recommend Windows users to install RStudio through Conda. The only build that is available (from `defaults` channel) is restricted to R 3.x.  If you are okay with that, then the following appears sufficient to co-install:

```bash
mamba create -n foo -c conda-forge -c defaults -c msys2 rstudio r-sjplot
```

This resolves to R 3.6.3 and sjplot v2.8.8.

Conda Forge does have a newer RStudio build (`rstudio-desktop`), but currently it does not build for **win-64**.
If you would like it built for Windows, I'd encourage you to [file an issue on the `conda-forge/rstudio-feedstock`](https://github.com/conda-forge/rstudio-feedstock/issues) requesting it.

---

So, **what do I recommend in practice**? Install a standalone version of RStudio, then launch it from the Conda R environment you wish to use with it. Something along these lines is outlined in [this StackOverflow thread](https://stackoverflow.com/q/38534383/570918).

**Comment by andreifoldes** [comment]
Thank you I did submit this. I will say that the rstudio-rsjplot co-install also doesn't seem to work on my Centos 7.6 computer and there the "workaround" doesn't work (no error message but only the top menu gui loads everything else is blank).  
This is only to highlight that the co-install could turn out to be useful in some situations.

I didn't know about mamba - I will try it out on both win and linux thx.

**Comment by mfansler** [comment]
@andreifoldes sounds like you still have an issue, so I'm reopening this. Could you please add debugging info about the setup that fails? Helpful things are:

- output of `conda list` from the environment
- output of `conda info`
- exact commands leading to issue (environment activation, launching of RStudio, R commands)
- error output

**Comment by mfansler** [comment]
Closing as stale.
